<a href="<?=$this->url('users/add')?>" class='btn btn-primary'>
    <?=$this->translate('__add_user')?>
</a>

<br/>
<br/>

<table>
    <thead>
        <tr>
            <th>
                <a href="<?php echo $this->url('users/list');?>/u.id/<?php echo $order;?>"><?=$this->translate('__user_id')?></a>
            </th>
            <th>
                <a href="<?php echo $this->url('users/list');?>/p.firstName/<?php echo $order;?>"><?=$this->translate('__user_firstname')?></a>
            </th>
            <th>
                <a href="<?php echo $this->url('users/list');?>/p.lastName/<?php echo $order;?>"><?=$this->translate('__user_lastname')?></a>
            </th>
            <th>
                <a href="<?php echo $this->url('users/list');?>/u.email/<?php echo $order;?>"><?=$this->translate('__user_email')?></a>
            </th>
            <th>
                <a href="<?php echo $this->url('users/list');?>/p.address/<?php echo $order;?>"><?=$this->translate('__user_address')?></a>
            </th>
            <th>
                <a href="<?php echo $this->url('users/list');?>/p.birthday/<?php echo $order;?>"><?=$this->translate('__user_birthday')?></a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php
    /* @var $user \Application\Entity\User */
    foreach($this->users as $user)
    {
        ?>
        <tr>
        <td>
            <?=$user['id']?>
        </td>
        <td>
            <?=$user['profile']['firstname']?>
        </td>
        <td>
            <?=$user['profile']['lastname']?>
        </td>
        <td>
            <a href='mailto:<?=$user['email']?>'>
                <?=$user['email']?>
            </a>
        </td>
        <td>
           <?=$user['profile']['address']?>
        </td>
        <td>
           <?=$user['profile']['birthday']->format('d-m-Y')?>
        </td>
        <td>
            <a href="<?=$this->url('users/edit', array('user_id'   =>  $user['id']))?>" class="btn btn-success">
                <?=$this->translate('__edit_user')?>
            </a>
           <a href="<?=$this->url('users/remove', array('user_id'   =>  $user['id']))?>" class="btn btn-danger">
            <?=$this->translate('__remove_user')?>
           </a>
        </td>
        </tr>
        <?php
    }
    ?>
    </tbody>
</table>